export type DashboardKpiId =
  | "kpi_human_hours_saved"
  | "kpi_time_to_market"
  | "kpi_content_waste"
  | "kpi_client_concentration"
  | "kpi_total_uploaded"
  | "kpi_total_created"
  | "kpi_ai_multiplier"
  | "kpi_period_growth"
  | "kpi_top_output_type";

export const DASHBOARD_KPI_DEFINITIONS: Record<
  DashboardKpiId,
  {
    title: string;
    definition: string;
    aliases: string[];
  }
> = {
  kpi_human_hours_saved: {
    title: "Est. Human Hours Saved",
    definition:
      "Manual video editing time eliminated. We assume 1 hour of raw content = 3 hours of manual editing work saved. This metric aggregates total uploaded duration across all clients and multiplies by 3.",
    aliases: [
      "human hours saved",
      "hours saved",
      "editing time saved",
      "manual hours eliminated",
      "manual hours",
      "est human hours",
      "estimated human hours",
    ],
  },
  kpi_time_to_market: {
    title: "Time-to-Market / Production Velocity",
    definition:
      "Average time from raw upload to live on social media. Lower is better — faster turnaround means faster content delivery to audiences. Calculated as the average hours between uploaded_at and published_at in the videos table.",
    aliases: [
      "time to market",
      "time-to-market",
      "production velocity",
      "turnaround time",
      "upload to live",
      "time to publish",
      "publishing speed",
    ],
  },
  kpi_content_waste: {
    title: "Content Waste Index",
    definition:
      "Volume of content generated by the AI that is never published. Calculated as (total created duration − total published duration). Lower waste indicates better alignment between AI output and what gets used.",
    aliases: [
      "content waste",
      "waste index",
      "unused content",
      "content not published",
      "content waste index",
      "wasted content",
      "unpublished content",
    ],
  },
  kpi_client_concentration: {
    title: "Client Concentration Risk",
    definition:
      "Percentage of total platform usage from the biggest client. High concentration indicates dependency risk — one client dominates volume. Diversification is healthier. Uses channel_processing_summary grouped by client_id.",
    aliases: [
      "client concentration",
      "concentration risk",
      "client risk",
      "biggest client",
      "client concentration risk",
      "top client share",
      "dominant client",
    ],
  },
  kpi_total_uploaded: {
    title: "Total Uploaded Volume",
    definition:
      "Raw amount of long-form and live content entering the system. Count and uploaded hours summed across all clients for each month from `monthly_processing_summary` (counts) and `monthly_duration_summary` (uploaded duration).",
    aliases: [
      "total uploaded volume",
      "total uploaded",
      "uploaded volume",
      "total uploads",
      "kpi total uploaded",
    ],
  },
  kpi_total_created: {
    title: "Total AI-Generated Output",
    definition:
      "Total processed output (videos with processed_at). Uses total_created/created_duration from monthly datasets — NOT uploaded. Represents all AI-processed content summed across all clients.",
    aliases: [
      "total created",
      "ai generated output",
      "total processed",
      "total ai output",
      "ai generated",
      "total ai generated",
      "processed output",
    ],
  },
  kpi_ai_multiplier: {
    title: "AI Content Multiplier",
    definition:
      "How much manual work the AI is saving. For example, 8x means 1 upload yields 8 assets on average. Higher multiplier = more leverage from each raw input. Ratio of total_created to total_uploaded from monthly_processing_summary.",
    aliases: [
      "ai multiplier",
      "content multiplier",
      "output per upload",
      "ai leverage",
      "ai content multiplier",
      "leverage ratio",
      "multiplier",
    ],
  },
  kpi_period_growth: {
    title: "Period-over-Period Growth",
    definition:
      "Growth or decline in adoption vs last period. Combines uploaded + published volume change. Positive = more activity; negative = slowdown.",
    aliases: [
      "period growth",
      "growth rate",
      "period over period",
      "month over month",
      "period-over-period",
      "period over period growth",
      "adoption growth",
      "growth trend",
    ],
  },
  kpi_top_output_type: {
    title: "Top Performing Output Type",
    definition:
      "The specific category (e.g., Shorts, Reels, Summary) driving the highest publish volume. Indicates what content types are most adopted. From output_type_processing_summary.",
    aliases: [
      "top output type",
      "top format",
      "best performing format",
      "top performing output type",
      "most published type",
      "best output type",
      "top content type",
    ],
  },
};

export function matchDashboardKpiId(question: string): DashboardKpiId | null {
  const q = question.toLowerCase();
  for (const [id, def] of Object.entries(DASHBOARD_KPI_DEFINITIONS) as Array<
    [DashboardKpiId, (typeof DASHBOARD_KPI_DEFINITIONS)[DashboardKpiId]]
  >) {
    if (def.aliases.some((a) => q.includes(a))) return id;
  }
  return null;
}
