/**
 * Sync dashboard data into RAG vector store
 * Builds text chunks from DB summaries and embeds them
 */

import { query } from "@/lib/db";
import { embedText } from "./rag-embeddings";
import { insertChunk, ensureRagTable, clearAllChunks } from "./rag-store";

export type SyncResult = {
  chunksCreated: number;
  errors: string[];
};

export async function syncRagStore(apiKey: string): Promise<SyncResult> {
  const errors: string[] = [];
  let chunksCreated = 0;

  await ensureRagTable();
  await clearAllChunks();

  const chunks: { source: string; type: string; content: string }[] = [];

  try {
    // 1. Schema / table descriptions (static knowledge)
    chunks.push({
      source: "schema",
      type: "schema",
      content: `Database schema for analytics: videos (video_id, client_id, channel_id, user_id, input_type_name, output_type_name, language_name, uploaded_at, processed_at, published_at, published_flag, published_platform, published_url). Summary tables: monthly_processing_summary (client_id, month, total_uploaded, total_created, total_published), monthly_duration_summary (client_id, month, total_uploaded_duration, total_created_duration, total_published_duration), channel_processing_summary, user_processing_summary, input_type_processing_summary, output_type_processing_summary, language_processing_summary, channel_wise_publishing_counts, channel_wise_publishing_duration.`,
    });

    // 2. KPI definitions (all 9 Page 1 KPIs)
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Est. Human Hours Saved: Manual video editing time eliminated. We assume 1 hour of raw content = 3 hours of manual editing work saved. Aggregates total uploaded duration across all clients and multiplies by 3. Queries monthly_duration_summary for total_uploaded_duration.",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Time-to-Market / Production Velocity: Average time from raw upload to live on social media. Lower is better — faster turnaround means faster content delivery to audiences. Calculated as the average hours between uploaded_at and published_at in the videos table.",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Content Waste Index: Volume of content generated by the AI that is never published. Calculated as (total created duration − total published duration). Lower waste indicates better alignment between AI output and what gets used. Queries monthly_duration_summary.",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Client Concentration Risk: Percentage of total platform usage from the biggest client. High concentration indicates dependency risk — one client dominates volume. Diversification is healthier. Uses channel_processing_summary grouped by client_id.",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Total Uploaded Volume: Raw amount of long-form and live content entering the system. Count and uploaded hours summed across all clients from monthly_processing_summary (counts) and monthly_duration_summary (uploaded duration).",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Total AI-Generated Output: Total processed output (videos with processed_at). Uses total_created and created_duration from monthly datasets — NOT uploaded. Represents all AI-processed content summed across all clients.",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "AI Content Multiplier: How much manual work the AI is saving. For example, 8x means 1 upload yields 8 assets on average. Higher multiplier = more leverage from each raw input. Ratio of total_created to total_uploaded from monthly_processing_summary.",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Period-over-Period Growth: Growth or decline in adoption vs last period. Combines uploaded + published volume change. Positive = more activity; negative = slowdown.",
    });
    chunks.push({
      source: "kpi",
      type: "definition",
      content:
        "Top Performing Output Type: The specific category (e.g., Shorts, Reels, Summary) driving the highest publish volume. Indicates what content types are most adopted. From output_type_processing_summary.",
    });

    // 3. Dashboard page context chunks
    chunks.push({
      source: "page_context",
      type: "page",
      content:
        "Dashboard Page 1 (CEO Overview) shows: Est. Human Hours Saved, Time-to-Market / Production Velocity, Content Waste Index, Client Concentration Risk, Total Uploaded Volume, Total AI-Generated Output, AI Content Multiplier, Period-over-Period Growth, Top Performing Output Type. Also shows a lifecycle trend chart (monthly uploads per client), pipeline funnel stats (uploaded → processed → published), and a feature adoption heatmap (client × output type matrix).",
    });
    chunks.push({
      source: "page_context",
      type: "page",
      content:
        "Dashboard Page 2 (Analysis & Funnel) shows: multi-dimensional bar chart cross-tabbing by client, channel, user, input type, output type, or language. Also shows donut chart for platform distribution, publishing funnel (3-stage: uploaded → processed → published), trend line chart with monthly progression, and a risk table with client-level data quality alerts.",
    });
    chunks.push({
      source: "page_context",
      type: "page",
      content:
        "Dashboard Page 3 (Channels) shows: operational efficiency matrix (channel performance), client and user performance drilldown, monthly contribution chart (billing view), client momentum tracker, client share donut, and language heatmap (client × language breakdown).",
    });
    chunks.push({
      source: "page_context",
      type: "page",
      content:
        "Dashboard Page 4 (Content Mix) shows: KPI insight cards, content amplification chart, platform hours chart, Sankey flow diagram (content transformation from input to output type), platform stacked chart by output type, and velocity chart (processing time metrics).",
    });
    chunks.push({
      source: "page_context",
      type: "page",
      content:
        "Dashboard Page 5 (Data Explorer) shows: raw videos table browser with search, filter, sort, and export. Also shows all 10 summary tables with peek and expand views, data quality alerts (automated checks for critical/warning/info issues), CSV/XLSX/JSON upload for data ingestion, and an Add Column UI to extend schema dynamically.",
    });

    // 4. Monthly aggregates
    const monthlyRes = await query<{ month: string; total_uploaded: string; total_created: string; total_published: string }>(
      `SELECT month, SUM(total_uploaded)::text AS total_uploaded, SUM(total_created)::text AS total_created, SUM(total_published)::text AS total_published
       FROM monthly_processing_summary GROUP BY month ORDER BY month DESC LIMIT 24`
    );
    if (monthlyRes.rows.length > 0) {
      const summary = monthlyRes.rows
        .map((r) => `${r.month}: uploaded ${r.total_uploaded}, processed ${r.total_created}, published ${r.total_published}`)
        .join("; ");
      chunks.push({
        source: "monthly",
        type: "summary",
        content: `Monthly processing totals (uploaded, processed, published): ${summary}`,
      });
    }

    // 5. Client breakdown
    const clientRes = await query<{ client_id: string; uploaded: string; created: string; published: string }>(
      `SELECT client_id, SUM(uploaded_count)::text AS uploaded, SUM(created_count)::text AS created, SUM(published_count)::text AS published
       FROM channel_processing_summary GROUP BY client_id ORDER BY SUM(published_count) DESC LIMIT 20`
    );
    if (clientRes.rows.length > 0) {
      const clientSummary = clientRes.rows
        .map((r) => `${r.client_id}: uploaded ${r.uploaded}, processed ${r.created}, published ${r.published}`)
        .join("; ");
      chunks.push({
        source: "clients",
        type: "summary",
        content: `Client processing summary (top by published): ${clientSummary}`,
      });
    }

    // 6. Channel leaders
    const channelRes = await query<{ channel_name: string; client_id: string; published: string }>(
      `SELECT channel_name, client_id, SUM(published_count)::text AS published
       FROM channel_processing_summary GROUP BY channel_name, client_id ORDER BY SUM(published_count) DESC LIMIT 15`
    );
    if (channelRes.rows.length > 0) {
      const channelSummary = channelRes.rows
        .map((r) => `${r.channel_name} (${r.client_id}): ${r.published} published`)
        .join("; ");
      chunks.push({
        source: "channels",
        type: "summary",
        content: `Top channels by published count: ${channelSummary}`,
      });
    }

    // 7. Platform distribution (simplified)
    try {
      const platformRes = await query<{ platform: string; hours: string }>(
        `WITH unpiv AS (
          SELECT 'YouTube' AS platform, SUM(CASE WHEN youtube_duration IS NOT NULL AND TRIM(COALESCE(youtube_duration::text,'')) != ''
            THEN EXTRACT(EPOCH FROM (youtube_duration::text::interval)) ELSE 0 END)/3600 AS hrs FROM channel_wise_publishing_duration
          UNION ALL SELECT 'Instagram', SUM(CASE WHEN instagram_duration IS NOT NULL AND TRIM(COALESCE(instagram_duration::text,'')) != ''
            THEN EXTRACT(EPOCH FROM (instagram_duration::text::interval)) ELSE 0 END)/3600 FROM channel_wise_publishing_duration
          UNION ALL SELECT 'X', SUM(CASE WHEN x_duration IS NOT NULL AND TRIM(COALESCE(x_duration::text,'')) != ''
            THEN EXTRACT(EPOCH FROM (x_duration::text::interval)) ELSE 0 END)/3600 FROM channel_wise_publishing_duration
        ) SELECT platform, ROUND(hrs::numeric, 1)::text AS hours FROM unpiv WHERE hrs > 0`
      );
      if (platformRes.rows.length > 0) {
        const platformSummary = platformRes.rows
          .map((r) => `${r.platform}: ${r.hours}h`)
          .join("; ");
        chunks.push({
          source: "platforms",
          type: "summary",
          content: `Published duration by platform (hours): ${platformSummary}`,
        });
      }
    } catch {
      /* skip platforms if table/columns differ */
    }

    // 8. Output types
    const outputRes = await query<{ output_type: string; created: string; published: string }>(
      `SELECT output_type, SUM(created_count)::text AS created, SUM(published_count)::text AS published
       FROM output_type_processing_summary GROUP BY output_type ORDER BY SUM(published_count) DESC LIMIT 10`
    );
    if (outputRes.rows.length > 0) {
      const outputSummary = (outputRes.rows as { output_type: string; created: string; published: string }[])
        .map((r) => `${r.output_type}: created ${r.created}, published ${r.published}`)
        .join("; ");
      chunks.push({
        source: "output_types",
        type: "summary",
        content: `Output type usage (created, published): ${outputSummary}`,
      });
    }

    // Embed and insert each chunk
    for (const chunk of chunks) {
      try {
        const embedding = await embedText(chunk.content, apiKey);
        await insertChunk(chunk.source, chunk.type, chunk.content, embedding, {
          source: chunk.source,
          type: chunk.type,
        });
        chunksCreated++;
      } catch (e) {
        errors.push(`${chunk.source}/${chunk.type}: ${e instanceof Error ? e.message : String(e)}`);
      }
    }
  } catch (e) {
    errors.push(`Sync failed: ${e instanceof Error ? e.message : String(e)}`);
  }

  return { chunksCreated, errors };
}
