"use client";

import type { Page1KPIs } from "./types";
import KPICard from "./KPICard";
import { DefinitionButton } from "@/components/ui/DefinitionButton";
import { InsightButton } from "@/components/ui/InsightButton";

interface KPIGridProps {
  kpis: Page1KPIs;
}

const CARD_DEFINITIONS: Array<{
  key: keyof Page1KPIs;
  label: string;
  format: (kpis: Page1KPIs) => string;
  tooltip: string;
  trendKey: keyof Page1KPIs;
  improvementDirection: "higher" | "lower" | "none";
  /** Latest month value — shown as main value when available */
  formatLatestMonth?: (kpis: Page1KPIs) => string | undefined;
  currentMonthValue?: (kpis: Page1KPIs) => string | undefined;
  prevValue?: (kpis: Page1KPIs) => string | undefined;
  widgetId: string;
}> = [
  {
    key: "humanHoursSavedFormatted",
    label: "Est. Human Hours Saved",
    format: (k) => k.humanHoursSavedFormatted,
    formatLatestMonth: (k) => k.humanHoursCurrentFormatted,
    tooltip: "Manual video editing time eliminated. We assume 1 hour of raw content = 3 hours of manual editing work saved. This metric aggregates total uploaded duration across all clients and multiplies by 3.",
    trendKey: "humanHoursTrendPct",
    improvementDirection: "higher",
    widgetId: "kpi_human_hours_saved",
    currentMonthValue: (k) => k.humanHoursCurrentFormatted,
    prevValue: (k) => k.humanHoursPrevFormatted,
  },
  {
    key: "timeToMarketHours",
    label: "Time-to-Market / Production Velocity",
    format: (k) => `${k.timeToMarketHours}h`,
    formatLatestMonth: (k) => k.timeToMarketCurrentHours != null ? `${k.timeToMarketCurrentHours}h` : undefined,
    tooltip: "Average time from raw upload to live on social media. Lower is better — faster turnaround means faster content delivery to audiences.",
    trendKey: "timeToMarketTrendPct",
    improvementDirection: "lower",
    widgetId: "kpi_time_to_market",
    currentMonthValue: (k) => k.timeToMarketCurrentHours != null ? `${k.timeToMarketCurrentHours}h` : undefined,
    prevValue: (k) => k.timeToMarketPrevHours != null ? `${k.timeToMarketPrevHours}h` : undefined,
  },
  {
    key: "contentWasteFormatted",
    label: "Content Waste Index",
    format: (k) => k.contentWasteFormatted,
    formatLatestMonth: (k) => k.contentWasteCurrentFormatted,
    tooltip: "Volume of content generated by the AI that is never published. Calculated as (total created duration − total published duration). Lower waste indicates better alignment between AI output and what gets used.",
    trendKey: "contentWasteTrendPct",
    improvementDirection: "lower",
    widgetId: "kpi_content_waste",
    currentMonthValue: (k) => k.contentWasteCurrentFormatted,
    prevValue: (k) => k.contentWastePrevFormatted,
  },
  {
    key: "clientConcentrationPct",
    label: "Client Concentration Risk",
    format: (k) => `${k.clientConcentrationPct}%`,
    formatLatestMonth: (k) => k.clientConcentrationCurrentPct != null ? `${k.clientConcentrationCurrentPct}%` : undefined,
    tooltip: "Percentage of total platform usage from the biggest client. High concentration indicates dependency risk — one client dominates volume. Diversification is healthier.",
    trendKey: "clientConcentrationTrendPct",
    improvementDirection: "lower",
    widgetId: "kpi_client_concentration",
    currentMonthValue: (k) => k.clientConcentrationCurrentPct != null ? `${k.clientConcentrationCurrentPct}%` : undefined,
    prevValue: (k) => k.clientConcentrationPrevPct != null ? `${k.clientConcentrationPrevPct}%` : undefined,
  },
  {
    key: "totalUploadedCount",
    label: "Total Uploaded Volume",
    format: (k) => `${k.totalUploadedCount.toLocaleString()} (${k.totalUploadedDurationFormatted})`,
    formatLatestMonth: (k) => k.currentMonthUploaded != null && k.currentMonthUploadedDurationFormatted
      ? `${k.currentMonthUploaded.toLocaleString()} (${k.currentMonthUploadedDurationFormatted})` : undefined,
    tooltip: "Raw amount of long-form and live content entering the system. Count and uploaded hours summed across all clients for each month from monthly_processing_summary and monthly_duration_summary.",
    trendKey: "totalUploadedTrendPct",
    improvementDirection: "higher",
    widgetId: "kpi_total_uploaded",
    currentMonthValue: (k) => k.currentMonthUploaded != null ? k.currentMonthUploaded.toLocaleString() : undefined,
    prevValue: (k) => k.prevMonthUploaded != null ? k.prevMonthUploaded.toLocaleString() : undefined,
  },
  {
    key: "totalCreated",
    label: "Total AI-Generated Output",
    format: (k) => k.totalCreatedDurationFormatted
      ? `${k.totalCreated.toLocaleString()} (${k.totalCreatedDurationFormatted})`
      : k.totalCreated.toLocaleString(),
    formatLatestMonth: (k) => k.currentMonthCreated != null && k.currentMonthCreatedDurationFormatted
      ? `${k.currentMonthCreated.toLocaleString()} (${k.currentMonthCreatedDurationFormatted})` : k.currentMonthCreated != null ? k.currentMonthCreated.toLocaleString() : undefined,
    tooltip: "Total processed output (videos with processed_at). Uses total_created/created_duration from monthly datasets — NOT uploaded. Summed across all clients.",
    trendKey: "totalCreatedTrendPct",
    improvementDirection: "higher",
    widgetId: "kpi_total_created",
    currentMonthValue: (k) => k.currentMonthCreated != null ? (k.currentMonthCreatedDurationFormatted ? `${k.currentMonthCreated.toLocaleString()} (${k.currentMonthCreatedDurationFormatted})` : k.currentMonthCreated.toLocaleString()) : undefined,
    prevValue: (k) => k.prevMonthCreated != null ? k.prevMonthCreated.toLocaleString() : undefined,
  },
  {
    key: "aiContentMultiplier",
    label: "AI Content Multiplier",
    format: (k) => `${k.aiContentMultiplier}x`,
    formatLatestMonth: (k) => k.currentMonthMultiplier != null ? `${k.currentMonthMultiplier}x` : undefined,
    tooltip: "How much manual work the AI is saving. For example, 8x means 1 upload yields 8 assets on average. Higher multiplier = more leverage from each raw input.",
    trendKey: "aiMultiplierTrendPct",
    improvementDirection: "higher",
    widgetId: "kpi_ai_multiplier",
    currentMonthValue: (k) => k.currentMonthMultiplier != null ? `${k.currentMonthMultiplier}x` : undefined,
    prevValue: (k) => k.prevMonthMultiplier != null ? `${k.prevMonthMultiplier}x` : undefined,
  },
  {
    key: "periodOverPeriodGrowthPct",
    label: "Period-over-Period Growth (Δ%)",
    format: (k) => `${k.periodOverPeriodGrowthPct >= 0 ? "+" : ""}${k.periodOverPeriodGrowthPct}%`,
    formatLatestMonth: (k) => k.currentMonthCombined != null ? k.currentMonthCombined.toLocaleString() : undefined,
    tooltip: "Growth or decline in adoption vs last period. Combines uploaded + published volume change. Positive = more activity; negative = slowdown.",
    trendKey: "periodOverPeriodGrowthPct",
    improvementDirection: "none",
    widgetId: "kpi_pop_growth",
    currentMonthValue: (k) => k.currentMonthCombined != null ? k.currentMonthCombined.toLocaleString() : undefined,
    prevValue: (k) => k.prevMonthCombined != null ? k.prevMonthCombined.toLocaleString() : undefined,
  },
  {
    key: "topPerformingOutputType",
    label: "Top Performing Output Type",
    format: (k) => k.topPerformingOutputType,
    formatLatestMonth: (k) => k.topOutputCurrentMonth,
    tooltip: "The specific category (e.g., Shorts, Reels, Summary) driving the highest publish volume. Indicates what content types are most adopted.",
    trendKey: "topPerformingOutputType",
    improvementDirection: "none",
    widgetId: "kpi_top_output_type",
    currentMonthValue: (k) => k.topOutputCurrentMonth,
    prevValue: (k) => k.topOutputPrevMonth,
  },
];

export default function KPIGrid({ kpis }: KPIGridProps) {
  return (
    <div className="rounded-2xl p-3 glass-card">
      <div className="flex items-center justify-between mb-2 gap-2">
        <h4 className="text-[10px] font-bold uppercase tracking-wider text-gray-400 flex items-center gap-2">
          Executive Vital Signs
          <span className="flex-1 h-px bg-gray-100" />
        </h4>
        <div className="flex items-center gap-1">
          <DefinitionButton definition="Key performance indicators for the CEO dashboard. Each card has its own definition — click the ? on any card for details." />
          <InsightButton page="page1" widget="executive_vital_signs" title="Executive Vital Signs insight" />
        </div>
      </div>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-1.5">
        {CARD_DEFINITIONS.map((def) => {
          const trendVal =
            def.improvementDirection !== "none"
              ? (kpis[def.trendKey] as number)
              : null;
          const latestMonthValue = def.formatLatestMonth?.(kpis);
          const primaryValue = latestMonthValue ?? def.format(kpis);
          const allTimeValue = latestMonthValue ? def.format(kpis) : undefined;
          return (
            <KPICard
              key={def.key}
              label={def.label}
              value={primaryValue}
              allTimeValue={allTimeValue}
              tooltip={def.tooltip}
              trendPct={typeof trendVal === "number" ? trendVal : null}
              improvementDirection={def.improvementDirection}
              currentMonthValue={def.currentMonthValue?.(kpis)}
              prevValue={def.prevValue?.(kpis)}
              currentMonthLabel={kpis.currentMonthLabel}
              prevLabel={kpis.prevMonthLabel ?? "prev month"}
              insightPage="page1"
              insightWidget={def.widgetId}
            />
          );
        })}
      </div>
    </div>
  );
}
